# Generated by Django 6.0.4 on 2026-04-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diaries", "0003_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="diaryentry",
            name="diary_picture",
            field=models.ImageField(blank=True, null=True, upload_to="diary_pics/"),
        ),
    ]
